name: Events demo 1
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: output test
        uses: actions/checkout@v3
      - run: echo "test is running"
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: output lint
        uses: actions/checkout@v3
      - run: echo "lint is running"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.1.2

      - name: Output build
        run: echo "building"

      - name: Build project
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: distfiles
          path: |
            dist
            package.json

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment boltey re public
        uses: actions/checkout@v3
      - run: echo "deploying"
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: Deploy code
        run: echo "deploying..."
